import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>Lister | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>About</h1>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam
          nesciunt tempore ducimus delectus, quo voluptatem commodi quia
          consequuntur dignissimos esse quidem? Voluptates illum perferendis
          explicabo fuga. Similique repellat sed id accusantium eligendi
          exercitationem, ducimus commodi ipsum excepturi, ratione porro. Quis,
          natus. Quod soluta officia ducimus omnis, illum minus consequuntur cum
          perferendis molestiae exercitationem similique possimus nobis.
          Voluptates.
        </p>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam
          nesciunt tempore ducimus delectus, quo voluptatem commodi quia
          consequuntur dignissimos esse quidem? Voluptates illum perferendis
          explicabo fuga. Similique repellat sed id accusantium eligendi
          exercitationem, ducimus commodi ipsum excepturi, ratione porro. Quis,
          natus. Quod soluta officia ducimus omnis, illum minus consequuntur cum
          perferendis molestiae exercitationem similique possimus nobis.
          Voluptates.
        </p>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam
          nesciunt tempore ducimus delectus, quo voluptatem commodi quia
          consequuntur dignissimos esse quidem? Voluptates illum perferendis
          explicabo fuga. Similique repellat sed id accusantium eligendi
          exercitationem, ducimus commodi ipsum excepturi, ratione porro. Quis,
          natus. Quod soluta officia ducimus omnis, illum minus consequuntur cum
          perferendis molestiae exercitationem similique possimus nobis.
          Voluptates.
        </p>
      </div>
    </>
  );
}
