import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/dist/client/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lister | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Main Page</h1>
      <p className={styles.text}>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde,
        temporibus similique! Ex illo voluptates eum ratione quos. Distinctio
        minima inventore praesentium voluptatibus commodi incidunt accusantium
        cumque voluptas nam, quis a reiciendis necessitatibus? In, sunt
        doloremque ipsam illum vitae dolorum repellat reiciendis ipsum eos at
        inventore nihil ea corrupti alias, possimus sit consequatur asperiores!
        Commodi, sequi.
      </p>
      <p className={styles.text}>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde,
        temporibus similique! Ex illo voluptates eum ratione quos. Distinctio
        minima inventore praesentium voluptatibus commodi incidunt accusantium
        cumque voluptas nam, quis a reiciendis necessitatibus? In, sunt
        doloremque ipsam illum vitae dolorum repellat reiciendis ipsum eos at
        inventore nihil ea corrupti alias, possimus sit consequatur asperiores!
        Commodi, sequi.
      </p>
      <p className={styles.text}>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde,
        temporibus similique! Ex illo voluptates eum ratione quos. Distinctio
        minima inventore praesentium voluptatibus commodi incidunt accusantium
        cumque voluptas nam, quis a reiciendis necessitatibus? In, sunt
        doloremque ipsam illum vitae dolorum repellat reiciendis ipsum eos at
        inventore nihil ea corrupti alias, possimus sit consequatur asperiores!
        Commodi, sequi.
      </p>
      <Link href="/Lists">
        <a className={styles.btn}>All Lists</a>
      </Link>
    </div>
  );
}
